#!/usr/bin/env bash
# setting up a ngix web server
sudo apt -y update
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chgrp -R ubuntu /usr/share/nginx/html
sudo chmod -R g+w /usr/share/nginx/html
echo "Holberton School" > /var/www/html/index.html
# adding a new redirect page
#changing the default nginx file to redirect to the disired link
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' #restarting the server
sudo service nginx start
