#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times but hi for the 9th
counter=1

until [ $counter -eq 10 ]
do
    echo "Holberton School"
    let counter+=1
    if [ "$counter" -eq 9 ]
    then
        echo "Hi"
    fi
done
