#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 atimes
counter=1
while [ $counter -le 10 ]
do
   echo "Holberton School"
   let counter+=1
   if [ "$counter" -eq 4 ]
      then
         echo "bad luck"
      fi
   if [ "$counter" -eq 8 ]
      then
         echo "good luck"
      fi
done
