#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 atimes
counter=1
while [ $counter -le 10 ]
do

   if [ "$counter" -eq 4 ]
      then
         echo "bad luck"
   elif [ "$counter" -eq 8 ]
      then
         echo "good luck"
      else
         echo "$counter"
   fi
   let counter+=1
done
