#!/usr/bin/env bash
#script that displays the time for 12 hours and 59 minutes
hours=0
minutes=1
while [ "$hours" -le 12 ]
do
    echo "Hour: $hours"
    while [ "$minutes" -lt 60 ]
        do
            echo "$minutes"
            let minutes+=1
        done
    let hours+=1
done
        