#!/usr/bin/env bash
#script that gives you information about the holbertonschool FILE.
FILE="holbertonschool"
if [ -e "$FILE" ]
    then
        echo "holbertonschool file exists"
        if [ -f "$FILE" ]
            then
                echo "holbertonschool is a regular file"
        fi
        if [ -s "$FILE" ]
            then
                echo "holbertonschool file is not empty"
        elif ! [ -s "$FILE" ]
            then
                echo "holbertonschool file is empty"
        fi
elif ! [ -e "$FILE" ]
    then
        echo "holbertonschool file does not exist"
fi
