#!/usr/bin/env bash
#script that gives you information about the holbertonschool file.
file=holbertonschool
if [ -e file ]
    then
        echo "holbertonschool file exists"
        if [ -f file ]
            then
                echo "holbertonschool is a regular file"
        fi
        if [ -s file ]
            then
                echo "holbertonschool file is not empty"
        elif ! [ -s file ]
            then
                echo "holbertonschool file is empty"
        fi
elif ! [ -e file ]
    then
        echo "holbertonschool file does not exist"
fi
