#!/usr/bin/env bash
# nstall the ufw firewall and setup a few rules on web-01.
sudo apt -y install ufw
sudo ufw default deny incoming
sudo ufw allow ssh
sudo ufw allow http
sudo ufw allow https
sudo ufw enable
sudo service ufw restart
