#!/usr/bin/env bash
# test script will change your localhost ip and facebook too
cp /etc/hosts hosts.new
sed -i -e 's/127.0.0.1/127.0.0.2/' hosts.new
echo "8.8.8.8 facebook.com" >> hosts.new
cat hosts.new > /etc/hosts
rm -rf hosts.new


