#!/usr/bin/env bash
# Fix this container so that Nginx is running as the nginx user.
sudo pkill nginx
sudo chown nginx:nginx /etc/nginx/nginx.conf
sudo chmod u+r /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx start
